services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    DigipolisGent\SettingBundle\FieldType\StringFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\FieldType\DisabledStringFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\FieldType\DisabledIntegerFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\FieldType\BooleanFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\FieldType\IntegerFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\FieldType\FileLocationFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\Service\FieldTypeServiceCollector:
        calls:
            - ['collectFieldTypes', [!tagged field_type]]
    DigipolisGent\SettingBundle\EventListener\DynamicSettingImplementationRelationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    DigipolisGent\SettingBundle\Form\Type\ConfigFormType:
        tags:
            - { name: form.type}
    DigipolisGent\SettingBundle\Service\FormService:
    DigipolisGent\SettingBundle\Service\DataTypeCollector:
        calls:
            - ['collectDataTypes', [!tagged data_type_provider]]
    DigipolisGent\SettingBundle\Service\DataValueService:
    DigipolisGent\SettingBundle\DataFixtures\ORM\LoadDataTypes:
    DigipolisGent\SettingBundle\DataFixtures\ORM\LoadEntityTypes:
